# fly.toml app configuration file generated for gala-playground on 2026-03-07T08:57:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gala-playground'
primary_region = 'lax'

[build]
  image = 'maxmtmn/gala-playground:latest'

[env]
  BIND_ALL = '1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 2
  memory_mb = 2048
